from __future__ import annotations

import json
import zipfile
from pathlib import Path
from typing import Any

import pandas as pd

from app.config import settings
from app.schemas.graph import GraphSchema
from app.schemas.project import ExportBundle
from app.services.graph_builder import node_id


REQUIRED_EXPORT_FILES = [
    "schema.json",
    "graph_nodes.csv",
    "graph_edges.csv",
    "networkx_builder.py",
    "pyg_dataset.py",
    "graphify_baseline.ipynb",
]


class CodeGenerator:
    def generate(self, project_id: str, filepath: str, schema: GraphSchema) -> ExportBundle:
        export_dir = Path(settings.EXPORT_DIR) / project_id
        export_dir.mkdir(parents=True, exist_ok=True)
        df = pd.read_csv(filepath)

        nodes_df, edges_df = self._build_tables(df, schema)
        schema_path = export_dir / "schema.json"
        nodes_path = export_dir / "graph_nodes.csv"
        edges_path = export_dir / "graph_edges.csv"
        builder_path = export_dir / "networkx_builder.py"
        pyg_path = export_dir / "pyg_dataset.py"
        notebook_path = export_dir / "graphify_baseline.ipynb"
        zip_path = export_dir / f"graphify_export_{project_id}.zip"

        schema_path.write_text(schema.model_dump_json(indent=2), encoding="utf-8")
        nodes_df.to_csv(nodes_path, index=False)
        edges_df.to_csv(edges_path, index=False)
        builder_path.write_text(self._networkx_builder_code(schema), encoding="utf-8")
        pyg_path.write_text(self._pyg_dataset_code(schema), encoding="utf-8")
        notebook_path.write_text(self._notebook_json(schema), encoding="utf-8")

        with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
            for filename in REQUIRED_EXPORT_FILES:
                archive.write(export_dir / filename, arcname=filename)

        return ExportBundle(project_id=project_id, zip_path=str(zip_path), files=REQUIRED_EXPORT_FILES)

    def _build_tables(self, df: pd.DataFrame, schema: GraphSchema) -> tuple[pd.DataFrame, pd.DataFrame]:
        node_rows: dict[str, dict[str, Any]] = {}
        edge_rows: list[dict[str, Any]] = []
        for _, row in df.iterrows():
            for node_type in schema.node_types:
                value = row.get(node_type.source_column)
                if pd.isna(value):
                    continue
                current_node_id = node_id(node_type.name, value)
                node_rows[current_node_id] = {
                    "node_id": current_node_id,
                    "node_type": node_type.name,
                    "source_column": node_type.source_column,
                    "source_value": value,
                    **{
                        feature: row.get(feature)
                        for feature in node_type.feature_columns
                        if feature in df.columns and not pd.isna(row.get(feature))
                    },
                }
            for edge_type in schema.edge_types:
                if len(edge_type.source_columns) < 2:
                    continue
                source_column, target_column = edge_type.source_columns[:2]
                source_value = row.get(source_column)
                target_value = row.get(target_column)
                if pd.isna(source_value) or pd.isna(target_value):
                    continue
                edge_rows.append(
                    {
                        "source_id": node_id(edge_type.source, source_value),
                        "target_id": node_id(edge_type.target, target_value),
                        "relation": edge_type.relation,
                    }
                )
        return pd.DataFrame(node_rows.values()), pd.DataFrame(edge_rows)

    def _networkx_builder_code(self, schema: GraphSchema) -> str:
        schema_json = json.dumps(schema.model_dump(), indent=2)
        return f'''# Auto-generated by Graphify AI
import json
import sys

import networkx as nx
import pandas as pd


SCHEMA = json.loads(r"""{schema_json}""")


def node_id(node_type, value):
    return f"{{node_type}}:{{value}}"


def build_graph(csv_path: str) -> nx.MultiDiGraph:
    df = pd.read_csv(csv_path)
    graph = nx.MultiDiGraph()

    for _, row in df.iterrows():
        for node_type in SCHEMA["node_types"]:
            source_column = node_type["source_column"]
            value = row.get(source_column)
            if pd.isna(value):
                continue
            graph.add_node(
                node_id(node_type["name"], value),
                node_type=node_type["name"],
                source_column=source_column,
                source_value=value,
            )

        for edge_type in SCHEMA["edge_types"]:
            if len(edge_type["source_columns"]) < 2:
                continue
            source_column, target_column = edge_type["source_columns"][:2]
            source_value = row.get(source_column)
            target_value = row.get(target_column)
            if pd.isna(source_value) or pd.isna(target_value):
                continue
            graph.add_edge(
                node_id(edge_type["source"], source_value),
                node_id(edge_type["target"], target_value),
                relation=edge_type["relation"],
            )

    return graph


if __name__ == "__main__":
    csv_path = sys.argv[1] if len(sys.argv) > 1 else "your_data.csv"
    graph = build_graph(csv_path)
    print(f"Graph: {{graph.number_of_nodes()}} nodes, {{graph.number_of_edges()}} edges")
'''

    def _pyg_dataset_code(self, schema: GraphSchema) -> str:
        schema_json = json.dumps(schema.model_dump(), indent=2)
        return f'''# Auto-generated by Graphify AI
import json

import pandas as pd


SCHEMA = json.loads(r"""{schema_json}""")


def _node_ids(df, source_column):
    return [str(value) for value in df[source_column].dropna().unique()]


def _feature_matrix(df, source_column, ids, feature_columns):
    import torch

    usable = [column for column in feature_columns if column in df.columns]
    if not usable:
        return torch.ones((len(ids), 1), dtype=torch.float)

    frame = df.drop_duplicates(source_column).set_index(source_column).reindex(ids)[usable]
    frame = pd.get_dummies(frame, dummy_na=True).fillna(0)
    return torch.tensor(frame.to_numpy(dtype=float), dtype=torch.float)


def build_hetero_data(csv_path: str):
    import torch
    from torch_geometric.data import HeteroData

    df = pd.read_csv(csv_path)
    data = HeteroData()
    id_maps = {{}}

    for node_type in SCHEMA["node_types"]:
        source_column = node_type["source_column"]
        ids = _node_ids(df, source_column)
        id_maps[node_type["name"]] = {{value: index for index, value in enumerate(ids)}}
        data[node_type["name"]].x = _feature_matrix(
            df,
            source_column,
            ids,
            node_type.get("feature_columns", []),
        )

    for edge_type in SCHEMA["edge_types"]:
        if len(edge_type.get("source_columns", [])) < 2:
            continue
        source_column, target_column = edge_type["source_columns"][:2]
        source_name = edge_type["source"]
        target_name = edge_type["target"]
        source_map = id_maps[source_name]
        target_map = id_maps[target_name]

        source_indices = []
        target_indices = []
        for _, row in df.iterrows():
            source_value = str(row[source_column])
            target_value = str(row[target_column])
            if source_value in source_map and target_value in target_map:
                source_indices.append(source_map[source_value])
                target_indices.append(target_map[target_value])

        edge_index = torch.tensor([source_indices, target_indices], dtype=torch.long)
        data[(source_name, edge_type["relation"].lower(), target_name)].edge_index = edge_index

    return data


if __name__ == "__main__":
    print("Graphify AI PyG dataset helper")
    print("Schema:", SCHEMA["name"])
    print("Node types:", [node["name"] for node in SCHEMA["node_types"]])
    print("Edge types:", [(edge["source"], edge["relation"], edge["target"]) for edge in SCHEMA["edge_types"]])
'''

    def _notebook_json(self, schema: GraphSchema) -> str:
        cells = [
            markdown_cell(
                "# Graphify AI Baseline Notebook\n"
                "This notebook is a starter artifact generated from the selected graph schema. "
                "It is meant for quick experimentation, not final model selection."
            ),
            code_cell(
                "import json\n"
                "import pandas as pd\n"
                "from pathlib import Path\n\n"
                "CSV_PATH = 'your_data.csv'\n"
                "SCHEMA_PATH = 'schema.json'\n\n"
                "df = pd.read_csv(CSV_PATH)\n"
                "schema = json.loads(Path(SCHEMA_PATH).read_text())\n"
                "print(df.shape)\n"
                "print(schema['name'])"
            ),
            code_cell(
                "from pyg_dataset import build_hetero_data\n\n"
                "try:\n"
                "    data = build_hetero_data(CSV_PATH)\n"
                "    print(data)\n"
                "    print('Metadata:', data.metadata())\n"
                "except ModuleNotFoundError as exc:\n"
                "    print('Install torch and torch-geometric to build HeteroData:', exc)"
            ),
            code_cell(self._baseline_code(schema)),
            markdown_cell(
                "## Modeling Notes\n"
                "- Use temporal splits when timestamps exist.\n"
                "- Compare graph baselines against a simple tabular model.\n"
                "- Watch for class imbalance and leakage columns before trusting metrics."
            ),
        ]
        notebook = {
            "cells": cells,
            "metadata": {
                "kernelspec": {
                    "display_name": "Python 3",
                    "language": "python",
                    "name": "python3",
                },
                "language_info": {"name": "python", "pygments_lexer": "ipython3"},
            },
            "nbformat": 4,
            "nbformat_minor": 5,
        }
        return json.dumps(notebook, indent=2)

    def _baseline_code(self, schema: GraphSchema) -> str:
        schema_name = schema.name.replace("'", "\\'")
        return (
            "# Reliable starter baseline using degree-style graph tables.\n"
            "from sklearn.linear_model import LogisticRegression\n"
            "from sklearn.metrics import classification_report\n"
            "from sklearn.model_selection import train_test_split\n\n"
            "label_candidates = [column for column in df.columns if column.lower() in {'label', 'target', 'is_fraud', 'fraud', 'churn', 'class', 'y', 'passed'}]\n"
            f"print('Selected schema: {schema_name}')\n"
            "if label_candidates:\n"
            "    label_col = label_candidates[0]\n"
            "    numeric = df.select_dtypes(include='number').drop(columns=[label_col], errors='ignore').fillna(0)\n"
            "    if numeric.empty:\n"
            "        print('No numeric features found for a quick supervised baseline.')\n"
            "    else:\n"
            "        X_train, X_test, y_train, y_test = train_test_split(numeric, df[label_col], test_size=0.2, random_state=42, stratify=df[label_col])\n"
            "        clf = LogisticRegression(max_iter=1000, class_weight='balanced')\n"
            "        clf.fit(X_train, y_train)\n"
            "        print(classification_report(y_test, clf.predict(X_test)))\n"
            "else:\n"
            "    print('No label column found. Use the exported HeteroData for unsupervised embeddings or link prediction.')"
        )


def markdown_cell(source: str) -> dict[str, Any]:
    return {"cell_type": "markdown", "metadata": {}, "source": source.splitlines(keepends=True)}


def code_cell(source: str) -> dict[str, Any]:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": source.splitlines(keepends=True),
    }
