from __future__ import annotations

import json
import zipfile
from pathlib import Path
from typing import Any

import pandas as pd

from app.config import settings
from app.schemas.graph import GraphSchema
from app.schemas.project import ExportBundle
from app.services.graph_builder import node_id


REQUIRED_EXPORT_FILES = ["schema.json", "graph_nodes.csv", "graph_edges.csv", "networkx_builder.py"]


class CodeGenerator:
    def generate(self, project_id: str, filepath: str, schema: GraphSchema) -> ExportBundle:
        export_dir = Path(settings.EXPORT_DIR) / project_id
        export_dir.mkdir(parents=True, exist_ok=True)
        df = pd.read_csv(filepath)

        nodes_df, edges_df = self._build_tables(df, schema)
        schema_path = export_dir / "schema.json"
        nodes_path = export_dir / "graph_nodes.csv"
        edges_path = export_dir / "graph_edges.csv"
        builder_path = export_dir / "networkx_builder.py"
        zip_path = export_dir / f"graphify_export_{project_id}.zip"

        schema_path.write_text(schema.model_dump_json(indent=2), encoding="utf-8")
        nodes_df.to_csv(nodes_path, index=False)
        edges_df.to_csv(edges_path, index=False)
        builder_path.write_text(self._networkx_builder_code(schema), encoding="utf-8")

        with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
            for filename in REQUIRED_EXPORT_FILES:
                archive.write(export_dir / filename, arcname=filename)

        return ExportBundle(project_id=project_id, zip_path=str(zip_path), files=REQUIRED_EXPORT_FILES)

    def _build_tables(self, df: pd.DataFrame, schema: GraphSchema) -> tuple[pd.DataFrame, pd.DataFrame]:
        node_rows: dict[str, dict[str, Any]] = {}
        edge_rows: list[dict[str, Any]] = []
        for _, row in df.iterrows():
            for node_type in schema.node_types:
                value = row.get(node_type.source_column)
                if pd.isna(value):
                    continue
                current_node_id = node_id(node_type.name, value)
                node_rows[current_node_id] = {
                    "node_id": current_node_id,
                    "node_type": node_type.name,
                    "source_column": node_type.source_column,
                    "source_value": value,
                    **{
                        feature: row.get(feature)
                        for feature in node_type.feature_columns
                        if feature in df.columns and not pd.isna(row.get(feature))
                    },
                }
            for edge_type in schema.edge_types:
                if len(edge_type.source_columns) < 2:
                    continue
                source_column, target_column = edge_type.source_columns[:2]
                source_value = row.get(source_column)
                target_value = row.get(target_column)
                if pd.isna(source_value) or pd.isna(target_value):
                    continue
                edge_rows.append(
                    {
                        "source_id": node_id(edge_type.source, source_value),
                        "target_id": node_id(edge_type.target, target_value),
                        "relation": edge_type.relation,
                    }
                )
        return pd.DataFrame(node_rows.values()), pd.DataFrame(edge_rows)

    def _networkx_builder_code(self, schema: GraphSchema) -> str:
        schema_json = json.dumps(schema.model_dump(), indent=2)
        return f'''# Auto-generated by Graphify AI
import json
import sys

import networkx as nx
import pandas as pd


SCHEMA = json.loads(r"""{schema_json}""")


def node_id(node_type, value):
    return f"{{node_type}}:{{value}}"


def build_graph(csv_path: str) -> nx.MultiDiGraph:
    df = pd.read_csv(csv_path)
    graph = nx.MultiDiGraph()

    for _, row in df.iterrows():
        for node_type in SCHEMA["node_types"]:
            source_column = node_type["source_column"]
            value = row.get(source_column)
            if pd.isna(value):
                continue
            graph.add_node(
                node_id(node_type["name"], value),
                node_type=node_type["name"],
                source_column=source_column,
                source_value=value,
            )

        for edge_type in SCHEMA["edge_types"]:
            if len(edge_type["source_columns"]) < 2:
                continue
            source_column, target_column = edge_type["source_columns"][:2]
            source_value = row.get(source_column)
            target_value = row.get(target_column)
            if pd.isna(source_value) or pd.isna(target_value):
                continue
            graph.add_edge(
                node_id(edge_type["source"], source_value),
                node_id(edge_type["target"], target_value),
                relation=edge_type["relation"],
            )

    return graph


if __name__ == "__main__":
    csv_path = sys.argv[1] if len(sys.argv) > 1 else "your_data.csv"
    graph = build_graph(csv_path)
    print(f"Graph: {{graph.number_of_nodes()}} nodes, {{graph.number_of_edges()}} edges")
'''
